In [1]:
import pydqalg as dq


a = dq.Quat(.5, [.5,-.5,.5])
b = dq.Quat(.7071, [0,0,.7071])
print("conj(a)", a.conj())
print("2b", 2*b)
print("a+b", a+b)
print("norm(a+b)", (a+b).norm())
print("inv(a+b)", (a+b).inv())
print("(a+b)*(a+b).inv()", (a+b)*(a+b).inv())
print("a-b", a-b)
print("(a*b).q2axisangle()", (a*b).q2axisangle())
print("(b*a).q2axisangle()", (b*a).q2axisangle())
print("(a*b).q2rotmat()", (a*b).q2rotmat())
print("(b*a).q2rotmat()", (b*a).q2rotmat())
print("(a*b).q2rollpitchyaw()", (a*b).q2rollpitchyaw())
print("(b*a).q2rollpitchyaw()", (b*a).q2rollpitchyaw())


conj(a) Quat(0.500000, [-0.500000, 0.500000, -0.500000])
2b Quat(1.414200, [0.000000, 0.000000, 1.414200])
a+b Quat(1.207100, [0.500000, -0.500000, 1.207100])
norm(a+b) 1.8477502049790173
inv(a+b) Quat(0.353555, [-0.146448, 0.146448, -0.353555])
(a+b)*(a+b).inv() Quat(1.000000, [0.000000, 0.000000, 0.000000])
a-b Quat(-0.207100, [0.500000, -0.500000, -0.207100])
(a*b).q2axisangle() (array([ 0.        , -0.70710678,  0.70710678]), 3.141592653589793)
(b*a).q2axisangle() (array([0.70710678, 0.        , 0.70710678]), 3.141592653589793)
(a*b).q2rotmat() [[1. 2. 2.]
 [2. 1. 2.]
 [2. 2. 1.]]
(b*a).q2rotmat() [[1. 2. 2.]
 [2. 1. 2.]
 [2. 2. 1.]]
(a*b).q2rollpitchyaw() (1.1071487177940904, nan, 1.1071487177940904)
(b*a).q2rollpitchyaw() (1.1071487177940904, nan, 1.1071487177940904)


G:\MOHSIN work\reports n ppts\tidbit-notes\tidbit-libs\pydqalg.py:115: RuntimeWarning: invalid value encountered in arcsin
  p = np.arcsin(-R[2, 0])


In [1]:
norm = a.norm()

NameError: name 'a' is not defined

In [3]:
import numpy as np

na = np.array([1,2,3])
nb = np.array([3,2,1])
print(na*nb, sum(na*nb), np.inner(na,nb), np.dot(na,nb), \
      np.cross(na,nb), 2*na, np.multiply(2,nb))
np.inner?

[3 4 3] 10 10 10 [-4  8 -4] [2 4 6] [6 4 2]


Docstring:
inner(a, b)

Inner product of two arrays.

Ordinary inner product of vectors for 1-D arrays (without complex
conjugation), in higher dimensions a sum product over the last axes.

Parameters
----------
a, b : array_like
    If `a` and `b` are nonscalar, their last dimensions must match.

Returns
-------
out : ndarray
    `out.shape = a.shape[:-1] + b.shape[:-1]`

Raises
------
ValueError
    If the last dimension of `a` and `b` has different size.

See Also
--------
tensordot : Sum products over arbitrary axes.
dot : Generalised matrix product, using second last dimension of `b`.
einsum : Einstein summation convention.

Notes
-----
For vectors (1-D arrays) it computes the ordinary inner-product::

    np.inner(a, b) = sum(a[:]*b[:])

More generally, if `ndim(a) = r > 0` and `ndim(b) = s > 0`::

    np.inner(a, b) = np.tensordot(a, b, axes=(-1,-1))

or explicitly::

    np.inner(a, b)[i0,...,ir-1,j0,...,js-1]
         = sum(a[i0,...,ir-1,:]*b[j0,...,js-1,:])

In addition `a` o