In [1]:
import pydqalg as dq


qa = dq.Quat(.5, [ .5,-.5, .5])
qb = dq.Quat(.5, [-.5, .5, .5])
qc = dq.Quat(.7071, [0,0,.7071])
qd = dq.Quat(.866025, [0,0,.5])
print("qc.mulML", qc.mulML())
print("conj(a)", qa.conj())
print("2qb", 2*qb)
print("qa+qb", qa+qb)
print("norm(qa+qb)", (qa+qb).norm())
print("inv(qa+qb)", (qa+qb).inv())
print("(qa+qb)*(qa+qb).inv()", (qa+qb)*(qa+qb).inv())
print("qa-qb", qa-qb)
print("\n(qa*qb).q2axisangle()", (qa*qb).q2axisangle())
print("(qa*qb).q2rotmat()", (qa*qb).q2rotmat())
print("(qa*qb).q2YPR()", (qa*qb).q2YPR())
print("\n(qb*qa).q2axisangle()", (qb*qa).q2axisangle())
print("(qb*qa).q2rotmat()", (qb*qa).q2rotmat())
print("(qb*qa).q2YPR()", (qb*qa).q2YPR())
print("\n(qc*qd).q2axisangle()", (qc*qd).q2axisangle())
print("(qc*qd).q2rotmat()", (qc*qd).q2rotmat())
print("(qc*qd).q2YPR()", (qc*qd).q2YPR())



IndentationError: expected an indented block (pydqalg.py, line 261)

In [42]:
import numpy as np

print(dq.R2D(2.0943951023931957))
print(0.75**0.5 , 0.866025**2)

na=0
nb = np.array([1,2,3])
nc = np.array([4,5,6])
nd = np.array([ [7,8,9], [10,11,12], [13,14,15] ])

print(nb*nc, sum(nb*nc), np.inner(nb,nc), np.dot(nb,nc), \
      np.cross(nb,nc), 2*nb, np.multiply(2,nc))

print( np.shape([[nc]][0]), nc.reshape(3,1), nc.reshape(3,1).T, nd[0], nd )

Ra = np.hstack((na, -nb)); print(Ra)
Rb = np.hstack((nc.reshape(3,1), nd)); print(Rb)
RR = np.vstack((Ra, Rb)); print(RR)

# np.inner?

print(np.hstack((na, nb, nc)))
print(nc, nc.tolist(), np.eye(3))
a=np.eye(9); np.fill_diagonal(a,nc.tolist()); print(a)
print(len(nc))


120.00000000000001
0.8660254037844386 0.7499993006250001
[ 4 10 18] 32 32 32 [-3  6 -3] [2 4 6] [ 8 10 12]
(1, 3) [[4]
 [5]
 [6]] [[4 5 6]] [7 8 9] [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
[ 0 -1 -2 -3]
[[ 4  7  8  9]
 [ 5 10 11 12]
 [ 6 13 14 15]]
[[ 0 -1 -2 -3]
 [ 4  7  8  9]
 [ 5 10 11 12]
 [ 6 13 14 15]]
[0 1 2 3 4 5 6]
[4 5 6] [4, 5, 6] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 6.]]
3


In [4]:
def fun1(n):
    return n if n>0 else -n

print(fun1(1))
print(fun1(0))
print(fun1(1))



1
0
1


In [8]:
dqa = dq.DualQuat(qa, qc)
dqb = dq.DualQuat(qb, qd)
dqc = dq.DualQuat(dq.Quat(1, [0,0,0]), dq.Quat(0, [-1,3,2]))
dqd = dq.DualQuat(qa, dq.Quat(0, [0,0,0]))

print(dqa+dqb)
print(dqa-dqb)
print(dqc*dqd)
print(dqd*dqc)

DualQuat(Quat(1.000000, [0.000000, 0.000000, 1.000000])
         + ε Quat(1.573125, [0.000000, 0.000000, 1.207100]))
DualQuat(Quat(0.000000, [1.000000, -1.000000, 0.000000])
         + ε Quat(-0.158925, [0.000000, 0.000000, 0.207100]))
DualQuat(Quat(0.500000, [0.500000, -0.500000, 0.500000])
         + ε Quat(1.000000, [2.000000, 3.000000, 0.000000]))
DualQuat(Quat(0.500000, [0.500000, -0.500000, 0.500000])
         + ε Quat(1.000000, [-3.000000, 0.000000, 2.000000]))
